version: "3.9"

services:
  fastapi:
    build: .
    container_name: fastapi
    command: uvicorn main:app --host 0.0.0.0
    volumes:
      - .:/app
    ports:
      - 8000:8000
    depends_on:
      - mongodb
  mongodb:
    image: mongo:5.0
    container_name: mongodb
    env_file:
      - env/db.env
